# Generated by Django 4.2.7 on 2025-07-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grid_size', models.IntegerField(default=32)),
                ('num_robots', models.IntegerField(default=5)),
                ('num_waste', models.IntegerField(default=20)),
                ('base_x', models.IntegerField(default=16)),
                ('base_y', models.IntegerField(default=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='created', max_length=10)),
                ('current_turn', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('carrying_waste', models.BooleanField(default=False)),
                ('strategy', models.CharField(default='explore', max_length=50)),
                ('memory', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='simulation.simulation')),
            ],
            options={
                'unique_together': {('simulation', 'robot_id')},
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('collected', models.BooleanField(default=False)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.robot')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_items', to='simulation.simulation')),
            ],
            options={
                'unique_together': {('simulation', 'x', 'y')},
            },
        ),
    ]
